### PR TITLE
ItemClickSupport

### PR DESCRIPTION
**Pull request by pmk2429**
Added **ItemClickSupport**; a custom decoupled listener for **RecyclerView** that can be called anywhere without having to mess around with the underlying Adapter. `ItemClickSupport`leverages the `ViewHolder`pattern and enforces the listener by getting the item view from the ViewHolder. 
This way we can create decoupled and east to test RecyclerView without actually passing around the listeners.

Added the project under `android/navigation`
Project root: `android/navigation/clicksupport`

**Files: **
**src**
- ItemClickSupport.java
- ItemListAdapter.java
- MainActivity.java

**layout**
- activity_main.xml
- list_item.xml

Added the tutorial in `overview.xml`(displays as item #12 in the tutorial in web page) as `ItemClickSupport`

### CODE REVIEW

**Comment by apuder** [comment]
First of all sorry for the late response. You did a very fine job structuring the tutorial to fit in with the other tutorials. You didn't change overview.xml. Without it the tutorial wouldn't be included on the main web page. Please make sure you can actually see your tutorial by following the "Generating the Web Page" steps mentioned in the README.

Apart from that I want to ask where the difference is between your tutorial and the one that is in navigation/list. That also uses a RecyclerView and does similar things as your tutorial. If your tutorial uses a best practice that navigation/list does not, perhaps it might be better to modify the existing tutorial.

**Comment by pmk2429** [comment]
I will make edits in overview.xml.
Well, ItemClickSupport is more of a decoupled version of handling clicks for RecyclerView and other ViewGroups or layouts. In a way, it can be referred to as a best practice for handling clicks without passing around onClickListeners.
I can close the PR if that's the case!

**Comment by apuder** [comment]
How about changing the navigation/list tutorial to include the click listener. I don't know if just the click listener warrants an extra tutorial.

**Comment by pmk2429** [comment]
Yes, it can certainly be done. I will edit this PR

**Comment by apuder** [comment]
Thanks!

**Pull request closed without merging**
